### PR TITLE
UTF8 for the win + lot of housekeeping

### PR DESCRIPTION
**Pull request by burner**
IMO if this is to end up in phobos UTF8 is the way to, this also means no DOMstring.

The rest is mostly boring housekeeping and formatting.

### CODE REVIEW

**Comment by ZILtoid1991** [comment]
Phobos is no longer the target, but I might think about it.

**Comment by burner** [comment]
> Phobos is no longer the target, but I might think about it.

What is the target now?

**Comment by ZILtoid1991** [comment]
> What is the target now?

I'm collecting some input on it from others.

**Comment by ZILtoid1991** [comment]
After some thinking, I came to this conclusion:
* Keep the `XMLChar` alias as a configurable template.
* Ditch the `DOMString` class and turn it into an alias `alias DOMString = const(XMLChar)[]`.

Even if I decide to later put it out as a Phobos candidate, it'll be easy to undo it, currently it might be more beneficial to keep some configurability of the library. Sometimes it's more practical to use UTF16 or something else (certain East Asian texts benefit from that), which is standard for XML DOM.

**Comment by ZILtoid1991** [comment]
Okay, it's time to swallow the poison pill for my projects.

Accepting it, but likely will keep the 0.2.1 version around for a while.

**Pull request merged**
